apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-webapp
  namespace: <NAMESPACE>
  labels:
    app: healthcare-webapp
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: healthcare-webapp
  template:
    metadata:
      labels:
        app: healthcare-webapp
    spec:
      containers:
        - name: healthcare-webapp
          image: leenab88/healthcare-webapp:v.<IMAGE_TAG>  # Specify the version if needed
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8082 # Port that the container listens on
