apiVersion: v1
kind: Service
metadata:
  name: healthcare-webapp-service
  namespace: <NAMESPACE>
spec:
  type: NodePort  # Expose the service using NodePort
  selector:
    app: healthcare-webapp
  ports:
    - port: 8082          # Port that the service listens on
      targetPort: 8082    # Port to forward to the container
      nodePort: 30089    # Choose a port between 30000-32767 for NodePort
